---
title: "Create new CSVs"
author: "Irene de la Torre"
date: '2023-01-15'
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyr)
library(readxl)
```

## Load data

```{r}
source <- "../network_data/"
source_users <- "../../network_data/"
```

### Matrix file

```{r eval = FALSE}
f1_Louvre_network <- read_csv(
  paste0(source, "Rooms.Matrix/Louvre_network.csv")
  )
```

### Room data

```{r}
f2_Louvre_network_Wi_Fi_miyajima_200528fin <- read_excel(
  paste0(
    source,
    "Rooms.Access.Points/Louvre_network+Wi-Fi_miyajima_200528fin.xlsx"
    )
  ) %>%
  rename(id_ap_1 = "ID_Access_Point")

head(f2_Louvre_network_Wi_Fi_miyajima_200528fin)
```

### Room data

```{r}
f2_Louvre_network_Wi_Fi_miyajima_200528fin <- read_excel(
  paste0(
    source,
    "Rooms.Access.Points/Louvre_network+Wi-Fi_miyajima_200528fin.xlsx"
    )
  ) %>%
  rename(id_ap_1 = "ID_Access_Point")

f3_WiFi_rename_miyajima_200528fin <- read_excel(
  paste0(
    source,
    "Rooms.Access.Points/Wi-Fi_rename_miyajima_200528fin.xlsx"
    )
  ) %>%
  rename(id_ap_1 = "No.") %>%
  select(c(id_ap_1, memo, mac)) %>%
  drop_na(id_ap_1)

f4_WIFI_LOUVRE_TRUE <- read_excel(
  paste0(source, "Rooms.Access.Points/WIFI_LOUVRE_TRUE.xlsx")
) %>%
  rename(
    id_ap_2 = Borne,
    mac_eth = "MAC ETH",
    mac_radio = "range MAC Radio", 
    location = "Emplacement") %>%
  select(c(id_ap_2, mac_eth, mac_radio, location))

f12_room_names_ids <- read_excel(
  paste0(source, "Rooms - museo and ids.xlsx")
)
```

### User data

It takes quite a long time to load

```{r}
f5A_Louvre_MIT_1_2017_11 <- read_csv(
  paste0(source_users,"Users.Locations/Louvre_MIT(11-2017)_v1.csv"))

f5A_Louvre_MIT_1_2017_12 <- read_csv(
  paste0(source_users,"Users.Locations/Louvre_MIT(12-2017)_v2.csv"))

f5A_Louvre_MIT_1_2018 <- read_csv(
  paste0(source_users,"Users.Locations/Louvre_MIT(1-2018)_v3.csv"))

head(f5A_Louvre_MIT_1_2018)
```


## Merge data

### f6 = f3 + f4 ------ merge by mac id

```{r}

source("../R/3_match_f3_f4_to_f6.R")

f6_id_1_2_matched <- create_f6(
  f3 = f3_WiFi_rename_miyajima_200528fin,
  f4 = f4_WIFI_LOUVRE_TRUE
  )

```

### f8 = f5 + f6 ------ merge by id_ap_2

It picks single names of the id_ap_2

```{r}

source("../R/4_match_f5_f6_to_f8.R")

f8_ap_matched_rooms <- create_f8(
  f5A_Louvre_MIT_1_2017_11,
  f5A_Louvre_MIT_1_2017_12,
  f5A_Louvre_MIT_1_2018,
  f6 = f6_id_1_2_matched,
  f12 = f12_room_names_ids
  )
```

### f9 = summary of 8

```{r}
source("../R/5_f8_to_summary_f9.R")
f9_ap_rooms <- create_f9(f8_ap_matched_rooms, "../output/f9_ap_rooms.csv")
```

### f11 = new user ids

```{r}
source("../R/7_f5_to_f11_new_user_ids.R")

f11_new_user_ids <- create_f11(
  f5A_Louvre_MIT_1_2017_11,
  f5A_Louvre_MIT_1_2017_12,
  f5A_Louvre_MIT_1_2018
)
```

### new user location

#### merge f8 with f5

```{r}
source("../R/6_merge_f5_f8_new_user.R")

f10_Louvre_MIT_1_2017_11 <- create_new_user_track(
  f5A_Louvre_MIT_1_2017_11,
  f8_ap_matched_rooms,
  f11_new_user_ids
  )

f10_Louvre_MIT_1_2017_12 <- create_new_user_track(
  f5A_Louvre_MIT_1_2017_12,
  f8_ap_matched_rooms,
  f11_new_user_ids
  )

f10_Louvre_MIT_1_2018 <- create_new_user_track(
  f5A_Louvre_MIT_1_2018,
  f8_ap_matched_rooms,
  f11_new_user_ids
  )


summary_f10(
  f10_Louvre_MIT_1_2017_11,
  f10_Louvre_MIT_1_2017_12,
  f10_Louvre_MIT_1_2018
  )

```

#### Export final format

```{r}
final_format_f10(
  f10_Louvre_MIT_1_2017_11,
  "f10_Louvre_MIT_1_2017_11.csv",
  "../output"
  )

final_format_f10(
  f10_Louvre_MIT_1_2017_12,
  "f10_Louvre_MIT_1_2017_12.csv",
  "../output"
  )

final_format_f10(
  f10_Louvre_MIT_1_2018,
  "f10_Louvre_MIT_1_2018.csv",
  "../output"
  )
```